#ifndef ERRORS_H
#define ERRORS_H

int GENERATE_ERROR();
int SHOW_HELP();
int FILE_ERROR();
int DIJKSTRA_ERROR();
int WEIGHT_ERROR();
int INPUT_NOT_INT();
int INPUT_OUT_OF_RANGE();
int INPUT_INT_ERR();
int INPUT_FORMAT_ERR();
int MALLOC_ERR();
int WYMIARY_ERROR();
#endif
